name: baza-app

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 2 --timeout 120 School_Management.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://school_user:school_password@db:5432/school_db
    depends_on:
      - db

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: ["tunnel", "run"]
    volumes:
      - ./cloudflared:/home/nonroot/.cloudflared
    depends_on:
      - web

volumes:
  postgres_data:
