services:
  - type: web
    name: cem-bouchnafa-omar
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn School_Management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 2
